clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
      path: ./plugin/
steps:
  - name: phpunit
    image: docker
    commands:
      - pwd
      - ls -asl ./plugin
      - docker run --rm -d -v ./plugin/:/var/www/html/custom/plugins/HhagLoginWithCode/ --name shopware_5 dockware/dev:latest
      - docker exec shopware_5 ls -asl /var/www/
      #- docker exec shopware_4 /var/www/html/vendor/bin/phpunit -c /var/www/html/custom/plugins/HhagLoginWithCode/phpunit.xml

      - docker stop shopware shopware_1 shopware_2 shopware_3 shopware_4 shopware_5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock