clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
      path: ./plugin/
steps:
  - name: phpunit
    image: docker
    commands:
      - docker run --rm -d --name shopware dockware/dev:latest
      - docker exec shopware ls -asl /var/www/
      - docker exec shopware mkdir -p /var/www/custom/plugins/HhagLoginWithCode
      - docker cp -r plugin/HhagLoginWithCode/. shopware:/var/www/custom/plugins/HhagLoginWithCode/.
      - docker exec shopware ls -asl /var/www/custom/plugins/HhagLoginWithCode
      #- docker exec shopware /var/www/vendor/bin/phpunit -c /var/www/custom/plugins/HhagLoginWithCode/phpunit.xml
      - docker stop shopware
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock